{{- if .Values.cozeWeb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencoze.fullname" . }}-nginx-config
  labels:
    {{- include "opencoze.labels" . | nindent 4 }}
data:
  nginx.conf: |
    worker_processes 1;
    events { worker_connections 1024; }

    http {
        include       mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;

        # setting client request body size limit - 0 means no limit
        client_max_body_size 0;

        include /etc/nginx/conf.d/*.conf;
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencoze.fullname" . }}-nginx-default-config
  labels:
    {{- include "opencoze.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        # Static resources
        location / {
            root   /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
            index  index.html index.htm;
            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;

            etag on;
            if_modified_since exact;
            add_header Cache-Control "no-cache";
            add_header Cache-Control "public, max-age=3600";
        }

        # API proxy
        location ~ ^/(api|v[1-3]|admin)(/|$) {
            proxy_pass http://{{ include "opencoze.fullname" . }}-server:8888;
            
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Timeout settings
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 600s;
            
            # SSL/TLS settings
            proxy_ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
            proxy_ssl_verify off;

            sub_filter ':8889' ':{{ .Values.cozeWeb.service.port }}/local_storage';
            sub_filter '{{ include "opencoze.fullname" . }}-minio:9000' '$http_host/local_storage';
            sub_filter_once off;
            sub_filter_types 'application/json' 'text/event-stream';
        }

        location /local_storage/ {
            if ($args ~* "(^|.*&)x-wf-file_name=[^&]*(&.*|$)") {
                set $args $1$2;
            }
            if ($args ~* "^x-wf-file_name=[^&]*$") {
                set $args "";
            }

            rewrite ^/local_storage/(.*)$ /$1 break;
            proxy_pass http://{{ include "opencoze.fullname" . }}-minio:9000;
            proxy_set_header Host {{ include "opencoze.fullname" . }}-minio:9000;
        }
    }
{{- end }}
